spring:
  application:
    name: shipping-quote-api
  datasource:
    url: jdbc:h2:file:./data/shipping;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: ${PORT:8080}
