CREATE TABLE shipping_quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weight_pounds DECIMAL(8, 2) NOT NULL,
    service_level VARCHAR(20) NOT NULL,
    base_cost DECIMAL(10, 2) NOT NULL,
    tax DECIMAL(10, 2) NOT NULL,
    total DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_shipping_quotes_created_at
    ON shipping_quotes (created_at DESC);
